package org.pancakelab.util;

public enum Pancakes {
    DARK_CHOCOLATE_PANCAKE,
    DARK_CHOCOLATE_WHIP_CREAM_HAZELNUTS_PANCAKE,
    DARK_CHOCOLATE_WHIP_CREAM_PANCAKE,
    MILK_CHOCOLATE_HAZELNUTS_PANCAKE,
    MILK_CHOCOLATE_PANCAKE
}